### ISSUE TITLE
Wiki Proyecto Solar

### ISSUE THREAD

**Issue by cristhianrosillo** [iamerroralpha/Scouts168#1]
El vínculo de la primera etapa está roto porque la publicación está pausada

**Comment by iamerroralpha** [comment]
lo acabo de checar, y si me sirve, podrías intentar de nuevo?

**Comment by cristhianrosillo** [comment]
Sí, me sigue apareciendo pausada. La diferencia es que en el celular sí me deja verlo y en la computadora se redirecciona inmediatamente a home.
